name: Deploy Backend (Render)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Trigger Render deployment
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
      
      - name: Wait for deployment to complete
        run: |
          echo "⏳ Waiting for Render deployment to complete..."
          sleep 30
      
      - name: Health check
        run: |
          echo "🏥 Performing health check..."
          
          # Try health check multiple times
          for i in {1..20}; do
            echo "Attempt $i/20..."
            
            if curl -f -s --max-time 30 "${{ secrets.RENDER_HEALTH_URL }}" > /dev/null; then
              echo "✅ Health check passed!"
              echo "🚀 The Cognisphere backend is live at:"
              echo "   ${{ secrets.RENDER_HEALTH_URL }}"
              echo ""
              echo "📚 API Documentation:"
              echo "   ${{ secrets.RENDER_HEALTH_URL }}/docs"
              echo ""
              echo "🔍 Available endpoints:"
              echo "   • GET  /healthz - Health check"
              echo "   • GET  /api/simulation/state - Simulation state"
              echo "   • POST /api/simulation/initialize - Initialize simulation"
              echo "   • POST /api/simulation/run - Start simulation"
              echo "   • POST /api/simulation/pause - Pause simulation"
              exit 0
            fi
            
            echo "⏳ Still waiting... ($i/20)"
            sleep 15
          done
          
          echo "❌ Health check failed after 20 attempts"
          echo "🔍 Checking if service is responding at all..."
          
          # Try basic connectivity
          if curl -s --max-time 10 "${{ secrets.RENDER_HEALTH_URL }}" > /dev/null; then
            echo "⚠️ Service is responding but health check failed"
            echo "🔧 This might be a temporary issue"
          else
            echo "❌ Service is not responding"
            echo "🚨 Deployment may have failed"
          fi
          
          exit 1
      
      - name: Test API endpoints
        run: |
          echo "🧪 Testing key API endpoints..."
          
          BASE_URL="${{ secrets.RENDER_HEALTH_URL }}"
          
          # Test health endpoint
          echo "Testing health endpoint..."
          if curl -f -s "$BASE_URL/healthz" | grep -q "ok"; then
            echo "✅ Health endpoint working"
          else
            echo "❌ Health endpoint failed"
          fi
          
          # Test API docs
          echo "Testing API documentation..."
          if curl -f -s "$BASE_URL/docs" > /dev/null; then
            echo "✅ API docs accessible"
          else
            echo "❌ API docs not accessible"
          fi
          
          # Test simulation state
          echo "Testing simulation state endpoint..."
          if curl -f -s "$BASE_URL/api/simulation/state" > /dev/null; then
            echo "✅ Simulation state endpoint working"
          else
            echo "❌ Simulation state endpoint failed"
          fi
      
      - name: Deployment summary
        run: |
          echo "🎉 Backend deployment completed!"
          echo ""
          echo "📊 Deployment Summary:"
          echo "   • Service: cognisphere-backend"
          echo "   • URL: ${{ secrets.RENDER_HEALTH_URL }}"
          echo "   • Environment: production"
          echo "   • LLM Mode: mock (scalable simulation)"
          echo "   • Memory Backend: networkx"
          echo "   • Vector Backend: faiss"
          echo ""
          echo "🔗 Integration:"
          echo "   • Frontend will connect to this backend"
          echo "   • CORS enabled for cross-origin requests"
          echo "   • Health monitoring active"
          echo ""
          echo "📈 Next steps:"
          echo "   1. Frontend deployment will use this backend"
          echo "   2. Monitor logs in Render dashboard"
          echo "   3. Test simulation initialization"
